export const EventCodes =
{
    Leave: 1,
    Move: 3,
    NewPlayer: 28,
    NewSimpleHarvestableObject: 37,
    NewSimpleHarvestableObjectList: 38,
    NewHarvestableObject: 39,
    HarvestableChangeState: 45,
    MobChangeState: 46,
    HarvestFinished: 60,
    Respawn: 86,
    RegenerationHealthChanged: 89,
    CharacterEquipmentChanged: 88,
    NewTreasureChest: 115,
    NewMob: 121,
    Mounted: 204,
    MountStart: 205,
    MountCancel: 206,
    NewRandomDungeon: 312,
    NewLootChest: 381,
    NewMistsCagedWisp: 518,
    MistsWispCageOpened: 519,
    FishingFinished: 345,
    NewFishingZoneObject: 348,    
    Track: 544,
    TrackNotFound: 550
}
